### ISSUE TITLE
Fixes the formatting of the latest release

### ISSUE THREAD

**Issue by judamar** [Mooling0602/BatterySaver-MCDR#2]
The latest release is a .zip file, it is not shown in the plugins catalog.

![image](https://github.com/Mooling0602/BatterySaver-MCDR/assets/87725312/871f9e35-cf0f-4771-b3f6-4476c0385138)

**Comment by Mooling0602** [comment]
Release v0.0.2 updated, you can now download from it directly, or wait for MCDReforged Plugins Catalogue update synchronously.
